### ISSUE TITLE
Why client_order_id must be unique?

### ISSUE THREAD

**Issue by zdytch** [alpacahq/alpaca-py#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I realize, this is an API-specific logic, not alpaca-py. So if there is a better place to discuss, please navigate me there.

The idea behind 'client_order_id' is to allow syncing client state with Alpaca state. Let's say we have a trading bot which makes decisions to submit and cancel orders in certain moments. The bot has its own already generated data structures for orders, with their ids. And those ids are really unique on the bot's side and are used as 'client_order_id' when submitting orders to Alpaca.

But what happens, when bot submits an order, then cancels it, then wants to submit it again? Alpaca responds 'client_order_id must be unique'. It seems wrong to me, when Alpaca tries to manage client ids. At the same time, Alpaca already has its own ids for managing its orders — the 'id' field. 

### Describe the solution you'd like.

So why not to leave 'client_order_id' field to be of responsibility on client's side? The 'client_order_id' field could be just a label, meaning nothing for Alpaca but very important for clients not to interfere with their logic. 

Examples from different brokers, where it works the described way:
- Interactive Brokers API: 'orderRef' field
- Binance API: 'newClientOrderId' field

**Comment by haxdds** [comment]
I've brought it up internally - will close this issue since it is not related to the SDK. I'll respond in this issue if I learn more.

**Comment by haxdds** [comment]
A better place to bring it up is the community slack.

**Comment by OlegRa** [comment]
@zdytch I don't know exactly but most probably they need unique `client_order_id` values because you have the [ability to request](https://alpaca.markets/docs/api-references/trading-api/orders/#get-an-order-by-client-order-id) orders using this ID. If you want to tag (label) your orders you have to use some schema that adds a unique part into the `client_order_id` with the ability to extract the tag itself like tag + GUID with a separator that will never be used by both tag and GUID.
