### ISSUE TITLE
Avoid locking pandas to v1

### ISSUE THREAD

**Issue by impredicative** [alpacahq/alpaca-py#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Is there any strong reason why the `pandas` requirement has to stay locked to v1? Can it be unlocked, so as to allow using pandas v2?

**Comment by sircambridge** [comment]
I agree. When bundling pandas, it's like a whole 1GB extra when using something like pyinstaller to make a stand alone executable for clients. Seems overkill if all we need is the dataframe module. Anyway, the alpaca golang sdk compiles down to 8MB as a stand alone executable, so I'm going with that for now unless pretty please can this be resolved.

**Comment by FyZyX** [comment]
Yeah, this is kinda brutal. A quick search through the package indicates that the version number could probably be bumped without any changes since the usage seems very limited. Obviously I haven't checked thoroughly, but this definitely starts to create versioning conflicts as other packages have already migrated.

To the point about pandas being a beefing dependency, I actually agree completely, and it would be great to actually make it an extra so that it can be optionally installed instead of forcing people to install it if they don't actually need it. If there is some reason that the version can't be bumped in the requirements, this could also allow users on v2 to just install this package without the extra dependency and handle the pandas part on their own.

**Comment by kchima** [comment]
Hey! Thanks for addressing this. I see that you mentioned that the release would be out 1-2 weeks ago, but it still looks like the latest release is still late April. Is there an ETA on this one?

**Comment by haxdds** [comment]
@kchima Pandas V2 is out in `v0.9.0`.
