### ISSUE TITLE
[Bug]: noisy model_* pydantic attributes

### ISSUE THREAD

**Issue by impredicative** [alpacahq/alpaca-py#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I get a snapshot using v0.12.0, there are noisy and unnecessary `model_*` attributes all over the place. This was not an issue with v0.10.0.

They can be listed by seeing:
```
[attr for attr in dir(snapshot) if attr.startswith('model_')]

['model_computed_fields', 'model_config', 'model_construct', 'model_copy', 'model_dump', 'model_dump_json', 'model_extra', 'model_fields', 'model_fields_set', 'model_json_schema', 'model_parametrized_name', 'model_post_init', 'model_rebuild', 'model_validate', 'model_validate_json', 'model_validate_strings']
```

This applies recursively to all pydantic objects.

### Expected Behavior

These internal model attributes should ideally be hidden via a leading underscore if they need to exist at all.

### SDK Version I encountered this issue in

0.12.0

### Steps To Reproduce

```markdown
snapshot = stock_historical_data_client.get_stock_snapshot(StockSnapshotRequest(symbol_or_symbols='TQQQ', feed=SIP))['TQQQ']
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by alessiocastrica** [comment]
Hi @impredicative this is not a bug, it's expected since you're using the python built-in function `dir()` which is returning a [list of all valid attributes in an object](https://docs.python.org/3/library/functions.html#dir). 
Since `snapshot` is an instance of a sub-class of a pydantic `BaseModel` it inherits all the attributes of a standard `BaseModel`, including the ones you listed. There's no code on alpaca-py to add any of those fields, and this is just related to the fact that we use pydantic for data validation.

I'm not sure what's your use case, but if you don't want to see those attributes, you simply don't need to use the `dir()` function. 
The representation of the snapshot object won't include them, and they're not included in the `model_fields` as well.
![Screenshot 2023-10-17 at 14 19 13](https://github.com/alpacahq/alpaca-py/assets/104512673/3dfcaceb-47fe-4bb5-8ec4-a6d8f95a744e)
