### ISSUE TITLE
[Bug]: Order stuck in pending_cancel

### ISSUE THREAD

**Issue by dsun615** [alpacahq/alpaca-py#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I do a TradingClient.cancel_orders(), my order get stuck in pending_cancel status. It may take a few minutes for it to go away itself. Sometime this issue doesn't happen at all. I do notice sometime it can happen on the orders page https://app.alpaca.markets/orders where you check the box to select all and cancel. I have one now currently stuck in pending_status the whole day. Order id c6ba2784-f809-4946-a483-42def039d1e2 in my paper account. However, it may have successfully cancelled by the time you look at it.

### Expected Behavior

I expect when you cancel, an order, or all orders that it will cancel and not get stuck. 

### SDK Version I encountered this issue in

alpaca-py: v0.13.6 

### Steps To Reproduce

```markdown
In the paper account.
Make sure to have multiple open positions. 

Prior to having open positions. I enter bracket orders for multiple stocks. When the orders get filled, there are the two order legs lefts for each of the bracket orders -the target and the stop loss.

The automation tries to exist out the position within 15 to 30 minutes by cancelling all orders and creating a new order OCO orders against the open positions. 

However, before I can get to creating the OCO orders, the existing orders get stuck in the 'pending_cancel' status when trying to cancel all orders. I didn't note the time of how long it takes for it to actually complete cancelling. I just notice when I go back to look at my logs, that my program failed due to pending_cancel. When I rerun at that time - about 30 minutes later or so after the cancel, my oco orders go through because the pending_cancel orders finally completed. I normally run this logic between 9:45AM - 10:15 EST. Not sure if the issue happens because its during peak trading time and a lot of orders are taking some time to complete?

--------------------------------
Sample Bracket order prior to having an open position.

symbol = 'T'
share_size = 100
limit_price = 16.20
take_profit = 17
stop_loss = 15.50

ALPACA_API_KEY = ''
ALPACA_SECRET_KEY = ''

stock_trading_client = TradingClient(ALPACA_API_KEY, ALPACA_SECRET_KEY)

order_req = LimitOrderRequest(symbol=symbol
							   , qty =share_size
							   , side=OrderSide.SELL
							   , type=OrderType.LIMIT
							   , time_in_force=TimeInForce.GTC
							   , limit_price=limit_price
							   , client_order_id = f'{datetime.utcnow().timestamp()}'
							   )

order_req.order_class = OrderClass.BRACKET
order_req.take_profit = TakeProfitRequest(limit_price=take_profit)                    
order_req.stop_loss = StopLossRequest(stop_price=stop_loss)

order = stock_trading_client.submit_order(order_data=order_req)

----------------------------------
After 15 or 30 minutes. I cancel the order to create a new updated order.


stock_trading_client.cancel_orders()
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

![pending_cancel_issue](https://github.com/alpacahq/alpaca-py/assets/65474523/c5ac94aa-9226-4b33-8383-db6114c2f8df)

**Comment by hiohiohio** [comment]
Seems this is not a bug. There are some limitations of timing when we change status of orders. We need to communicate with external exchanges for status change of orders. Therefore, depending on time especially outside of market hours, this situation could happen.

**Comment by MuseumsUniversitas** [comment]
**Bracket-to-trailing-stop replacement: cancel propagation delay causes systematic failures on paper trading**

Sharing data from a production paper trading system in case it helps. We cancel both OCO legs of a bracket order and then immediately submit a trailing stop to replace them. On paper trading, `qty_available` stays at 0 for **10–30+ seconds** after the cancel acknowledgment (204), causing the trailing stop submission to fail with "insufficient qty available." This is reproducible on every trade where a trailing stop is warranted.

**Observed behavior:**
- `cancel_order_by_id()` returns immediately (204)
- `get_open_position(symbol).qty_available` stays at 0 for 10–30s (paper trading)
- Any order submission during this window that requires available qty fails

**Our workaround:** We removed a synchronous 10-second poll (which always timed out on paper) and now retry the trailing stop submission every 10 seconds via our own fast-path loop, giving Alpaca 60 seconds of async runway before we give up and restore a standalone stop-limit as a fallback. This works, but it means every trailing stop takes 20–30 seconds to place — well after the price has already moved.

**The root cause we'd flag:** `DELETE /v2/orders/{id}` returns 204 before propagation completes. From the client side, the cancel looks done but `qty_available` tells a different story. Even a `pending_cancel → cancelled` status event via the WebSocket stream would let us submit immediately on confirmation rather than polling blind.

The longer-term fix is native trailing stop support as a bracket leg (requested on the forum since 2022). That would eliminate the cancel-and-replace pattern entirely.

**Environment:** alpaca-py, paper trading (`paper-api.alpaca.markets`), Python 3.13
